### PR TITLE
disable train travel detection

### PR DESCRIPTION
**Pull request by IcedDog**

### CODE REVIEW

**Comment by tizu69** [comment]
Hey @IcedDog,
I don't really understand what this does. Would you mind explaining what this is meant for?

**Comment by IcedDog** [comment]
it force the train to continue traveling as long as the track is connected to another track

**Comment by tizu69** [comment]
> it force the train to continue traveling as long as the track is connected to another track

Well yeah, but I don't see the point of this. Tried some things but nothing seems to have changed except when building a loop and maybe some intersections in it, sometimes the train stops the opposite way in the station and sometimes it just turns around, speeds up instantly faster than the set limit, drives around the track and then stops.

I doubt this is what you intended.

**Review by tizu69 — CHANGES_REQUESTED** [review]
- function unclear
- loops in track with switch to turn around cause weird behavior when stopping to station

**Comment by IcedDog** [comment]
Well, this is what I did in my fabric modification in order to make the train travel along extreme turns (e.g. extreme height changes and small turns over 180 degrees. It do a quick small flinch but no major problem) and I haven't encountered the loop problem on my side (fabric). It seems not to be working here, so nevermind. :sob:

It does cause weird behavior with too-extreme cases, but I did them intentionally (fun). I've never had any problem when building a normal track loop like a roller coaster.

I also notice what I'm trying to achieve doesn't really fit the mod's intention, so sorry for the inconvenience!:sob:

**Comment by tizu69** [comment]
No problem but thanks for your help!

**Pull request closed without merging**
